### ISSUE TITLE
Upcoming change to DelayedArray::realize()

### ISSUE THREAD

**Issue by hpages** [pfh/weitrix#1]
Hi Paul,

I'm the maintainer of the **DelayedArray** package. In the next few days I'm planning to make a small change to the behavior of `realize()` that could potentially affect packages that use this function (**weitrix** is one of them).

**What will change?**

Only the behavior of the default `realize()` method will change, and it will change only when the `BACKEND` argument is set to `NULL`. Right now (i.e. in **DelayedArray** <= 0.29.0), `realize(x, BACKEND=NULL)` realizes `x` in memory (as an ordinary array) and returns the in-memory array wrapped in a DelayedArray object. The change I'm considering is to get rid of the DelayedArray wrap, that is, to return the in-memory array naked.

Note that for any other `BACKEND` value, nothing will change, i.e. `realize()` will still be guaranteed to return a DelayedArray derivative (e.g. an HDF5Array object if `BACKEND` is set to `"HDF5Array"`).

**How will this affect your code?**

If it's important for your code that `realize()` _always_ returns a DelayedArray object or derivative, like it does at the moment, then simply replace any call to `realize(...)` with `DelayedArray(realize(...))`. This will preserve the current behavior even after the change. Note that calling the `DelayedArray()` constructor function on a DelayedArray object or derivative is a no-op. In other words, this extra step won't add the DelayedArray wrap again if there's already one.

**Where/when will this change happen?**

I will make this change to the `devel` branch of the **DelayedArray** package in the next few days. It will only (potentially) affect packages [in BioC 3.19](https://bioconductor.org/checkResults/3.19/bioc-LATEST/). Nothing will change in the `RELEASE_3_18` branch of **DelayedArray** (BioC 3.18).

Let me know if you have any question about this.

Thanks,
H.

**Comment by pfh** [comment]
This change seems to have been delayed, as the devel version of DelayedArray is still 0.29.0.

I'm not sure if the change will actually cause any problems. I recall a weird case where mixing DelayedArray and matrix caused errors, so there is a function where weitrix does deliberately ensure the delayedness of the x matrix matches the delayedness of the weights matrix using realize. The original problem may well have been fixed by now.

**Comment by hpages** [comment]
Yes this got a little bit delayed (I got distracted by other things).

I just pushed the change today. It's in **DelayedArray** 0.29.1.

> I'm not sure if the change will actually cause any problems.

Maybe it won't :crossed_fingers: I'll monitor the Bioconductor daily builds this week and make sure to identify any glitch related to this change.

**Comment by hpages** [comment]
Looks like this change didn't cause any problem: https://bioconductor.org/checkResults/3.19/bioc-LATEST/weitrix/
(The error on kunpeng2 is a different story and can be ignored for now.)

Closing this now.
